### ISSUE TITLE
Захардкожене посилання на bscscan

### ISSUE THREAD

**Issue by 17etro** [dexe-network/investing-dashboard#133]
![image](https://user-images.githubusercontent.com/55106769/200381392-cb9c99b0-ced5-4e92-8654-0728a64a8640.png)

pages/Success/index.ts
Помітив захардкожене посилання на bscscan

**Comment by edward-arinin-web-dev** [comment]
closed in [PR](https://github.com/dexe-network/investing-dashboard/pull/160)
