### ISSUE TITLE
Daily profit statistic error

### ISSUE THREAD

**Issue by edward-arinin-web-dev** [dexe-network/investing-dashboard#98]
if pool created within 24hours - daily profit will be "Infinity" because of pool creation date = 0.

in this case formula will look like this: pnl / 0 = Infinity.

<img width="353" alt="Снимок экрана 2022-10-12 в 11 52 16" src="https://user-images.githubusercontent.com/59831011/195298147-4556104d-75e2-43f9-91dd-66f035eecef6.png">
<img width="597" alt="Снимок экрана 2022-10-12 в 11 54 38" src="https://user-images.githubusercontent.com/59831011/195298174-e73434e7-80bf-4304-8a42-15b7b921ff08.png">

**Comment by saymon-develop** [comment]
Fix that in PR: https://github.com/dexe-network/investing-dashboard/pull/104

**Comment by edward-arinin-web-dev** [comment]
https://github.com/dexe-network/investing-dashboard/pull/104
